spring.application.name=multiwallet

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/multiwallet_db
spring.datasource.username=postgres
spring.datasource.password=Priyanshu@217

# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# JWT Authentication
jwt.secret=MyVerySecretKeyForMultiWalletApplication123456789
jwt.expiration=86400000

