package com.example.multiwallet.service.impl;

import com.example.multiwallet.service.MailService;
import jakarta.mail.internet.MimeMessage;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Service
public class MailServiceImpl implements MailService {
    private final JavaMailSender mailSender;

    public MailServiceImpl(JavaMailSender mailSender){
        this.mailSender = mailSender;
    }

    @Override
    public void sentOtp(String to, String otp) {
        sendOtp(to, otp, "Email Verification");
    }

    @Override
    public void sendOtp(String to, String otp, String purpose) {
        SimpleMailMessage mailMessage = new SimpleMailMessage();
        mailMessage.setTo(to);
        mailMessage.setSubject("MultiWallet - " + purpose + " OTP");
        mailMessage.setText("""
                Hello,
                
                Your OTP for MultiWallet (%s) is: %s
                This OTP is valid for 5 minutes.
                
                If you did not request this, please ignore this email.
                
                Regards,
                Team MultiWallet
                """.formatted(purpose, otp));
        mailSender.send(mailMessage);
    }

    @Override
    public void sendFinancialInsightEmail(String to, String userName, String insightsHtml) {
        try {
            MimeMessage mimeMessage = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(mimeMessage, true, "UTF-8");
            
            helper.setTo(to);
            helper.setSubject("📊 Your MultiWallet Monthly Financial Insights (AI Report)");
            
            String htmlBody = """
                    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px; background-color: #ffffff;">
                        <h2 style="color: #4F46E5; text-align: center;">🤖 MultiWallet AI Monthly Financial Digest</h2>
                        <p>Hi <strong>%s</strong>,</p>
                        <p>Here is your personalized monthly transaction analysis generated by our AI agent:</p>
                        <div style="background-color: #f8fafc; padding: 15px; border-left: 4px solid #4F46E5; margin: 20px 0; font-size: 14px; line-height: 1.6;">
                            %s
                        </div>
                        <hr style="border: none; border-top: 1px solid #eeeeee; margin: 20px 0;">
                        <p style="font-size: 12px; color: #6b7280; text-align: center;">This is an automated AI report sent by MultiWallet System.</p>
                    </div>
                    """.formatted(userName != null ? userName : "Valued User", insightsHtml.replace("\n", "<br/>"));

            helper.setText(htmlBody, true);
            mailSender.send(mimeMessage);
        } catch (Exception e) {
            System.err.println("Failed to send AI Insights email: " + e.getMessage());
            // Fallback to simple mail if HTML fails
            SimpleMailMessage fallback = new SimpleMailMessage();
            fallback.setTo(to);
            fallback.setSubject("MultiWallet Monthly Financial Insights (AI Report)");
            fallback.setText("Hi " + userName + ",\n\n" + insightsHtml);
            mailSender.send(fallback);
        }
    }
}
